import {lineChart} from '../../lab/dist/model-kit/chart.js';
export const clone = value => structuredClone(value);
export const e = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const number = value => Number(value).toLocaleString('en-GB',{maximumFractionDigits:1});
export const textSchema = {type:'string',maxLength:20000};
export const enumSchema = values => ({type:'string',enum:values,maxLength:100});
export const rangeSchema = (min,max,integer=false) => ({type:integer?'integer':'number',minimum:min,maximum:max});
export const objectSchema = (properties,required=Object.keys(properties)) => ({type:'object',properties,required,additionalProperties:false});
// Native validators retain domain invariants; this finite schema bounds portable
// authored material, including flat ancestry snapshots, before they are invoked.
export function jsonSchema(depth=7){const types=[{type:'null'},{type:'boolean'},{type:'number',minimum:-1e12,maximum:1e12},textSchema];if(depth){const child=jsonSchema(depth-1);types.push({type:'array',items:child,maxItems:256},{type:'object',additionalProperties:child});}return{anyOf:types};}
export function shape(value){if(value===null)return{anyOf:[{type:'null'},jsonSchema(4)]};if(Array.isArray(value)){const choices=[...new Map(value.map(v=>{const s=shape(v);return[JSON.stringify(s),s];})).values()];return{type:'array',maxItems:256,items:choices.length===1?choices[0]:choices.length?{anyOf:choices}:jsonSchema(4)};}if(typeof value==='object')return objectSchema(Object.fromEntries(Object.entries(value).map(([k,v])=>[k,shape(v)])));if(typeof value==='string')return textSchema;if(typeof value==='boolean')return{type:'boolean'};return rangeSchema(-1e9,1e9);}
export function nativeSchema(value,overrides={}) {const result=shape(value);Object.assign(result.properties,overrides);return result;}

export function ensure(test,message){if(!test)throw Error(message);}
export function checkNative(state,initial,validate){ensure(state&&typeof state==='object'&&!Array.isArray(state),'Expected an experiment object.');ensure(Object.keys(state).every(k=>Object.hasOwn(initial,k)),'Unknown experiment field.');validate(clone(state));}
export function base(route,title,description,initialState,validate,views,controls={},actions={},stateSchema=nativeSchema(initialState),status='active') {for(const view of Object.values(views))view.defaultControls??=view.controls.slice(0,2);return{id:'lab-'+route,version:1,title,description,status,defaultView:Object.keys(views)[0],initialState,stateSchema,validate:state=>checkNative(state,initialState,validate),controls,actions,views,fullTool:{url:`https://tools.matthewgarner.me/lab/${route}/`,encoding:'article-json-base64url'}};}
export const range=(label,path,min,max,step=1)=>({label,type:'range',path,min,max,step});
export const select=(label,path,options)=>({label,type:'select',path,options:Object.entries(options).map(([value,label])=>({value,label}))});
export const field=(label,path,maxLength=20000)=>({label,type:'textarea',path,maxLength,commit:true});
export const action=(label,id)=>({label,type:'action',action:id});
export function colors(ctx={}){const c=ctx.colors||{},dark=ctx.dark??ctx.theme==='dark';return{ink:c.ink||c.text||(dark?'#ece7da':'#252322'),paper:c.paper||c.background||(dark?'#232326':'#faf7ef'),accent:c.accent||(dark?'#c9e88d':'#725580'),muted:c.muted||(dark?'#b5afa7':'#686259'),line:c.line||(dark?'#55504e':'#d6cfc2')};}
export function wrap(value,width=70){return String(value??'').split(/\n/).flatMap(p=>{const words=p.split(/\s+/).flatMap(word=>word.length>width?word.match(new RegExp(`.{1,${Math.max(1,width)}}`,'gu')):word),lines=[];let line='';for(const w of words){if(line&&(line+' '+w).length>width){lines.push(line);line=w;}else line+=(line?' ':'')+w;}lines.push(line);return lines;});}
export function text(x,y,value,{width=70,size=18,weight=400,color='currentColor'}={}){return wrap(value,width).map((line,i)=>`<text x="${x}" y="${y+i*(size*1.4)}" font-size="${size}" font-weight="${weight}" fill="${e(color)}">${e(line)}</text>`).join('');}
export function figure(title,subtitle,draw,ctx={},height=460){const c=colors(ctx);return`<svg xmlns="http://www.w3.org/2000/svg" width="760" height="${height}" viewBox="0 0 760 ${height}" role="img" aria-label="${e(title)}"><rect width="760" height="${height}" fill="${e(c.paper)}"/><g fill="${e(c.ink)}" color="${e(c.ink)}" font-family="Arial, sans-serif">${text(28,38,title,{size:24,weight:700,width:52})}${text(28,72,subtitle,{size:15,width:90,color:c.muted})}${draw(c)}</g></svg>`;}
export function ledger(title,subtitle,rows,ctx={},foot=''){let y=118;const blocks=[];for(const row of rows){const lines=wrap(row.value,65);blocks.push(text(28,y,row.label,{size:16,weight:700,width:70}));y+=25;blocks.push(text(28,y,row.value,{size:18,width:65}));y+=lines.length*25+24;blocks.push(`<path d="M28 ${y-12} H732" stroke="var(--line)"/>`);}if(foot){blocks.push(text(28,y+6,foot,{size:15,width:88}));y+=wrap(foot,88).length*22+26;}return figure(title,subtitle,c=>blocks.join('').replaceAll('var(--line)',c.line),ctx,Math.max(220,y+24));}
export function chart(title,subtitle,series,ctx={},foot='',metrics=[]){const c=colors(ctx),width=704,height=260;let svg=lineChart(series.map((s,i)=>({...s,color:i?c.muted:c.accent})),{width,height,min:Math.min(0,...series.flatMap(s=>s.values))});svg=svg.replace('aria-hidden="true"','x="28" y="102" width="704" height="260"').replaceAll('var(--line)',c.line).replaceAll('var(--line-strong)',c.muted);const labels=series.map(s=>s.label).join(' · ');return figure(title,subtitle,()=>svg+text(28,388,labels,{size:16,width:85})+text(28,420,metrics.join(' · '),{size:18,width:75})+text(28,459,foot,{size:15,width:88}),ctx,484+Math.max(0,wrap(foot,88).length-1)*22);}
export function rowsHTML(rows){return'<dl>'+rows.map(r=>`<dt>${e(r.label)}</dt><dd>${e(r.value)}</dd>`).join('')+'</dl>';}
export function scaffold(route,title,description,initial,validate,rows,controls={},actions={},options={}) {const view=options.view||'argument';return base(route,title,description,initial,validate,{[view]:{title:options.viewTitle||title,description,controls:Object.keys(controls),render(state,ctx){const entries=rows(state);return{svg:ledger(title,state.problem||description,entries,ctx,options.limit||'Authored reasoning and fictional examples; evidence remains to be established.'),summary:entries.map(x=>x.label+': '+x.value).join(' ')}}}},controls,actions,options.schema||nativeSchema(initial),options.status||'active');}

export function canvas(title,subtitle,ctx,paint){const w=Math.max(320,Math.min(1100,ctx?.width||760)),c=colors(ctx),t=wrap(title,Math.floor((w-48)/13)),sub=wrap(subtitle,Math.floor((w-48)/8));const top=34+t.length*32+sub.length*22+20;const content=paint({w,c,top});const height=content.height??content.end+28;return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${height}" viewBox="0 0 ${w} ${height}" role="img" aria-label="${e(title)}"><rect width="${w}" height="${height}" fill="${e(c.paper)}"/><g fill="${e(c.ink)}" font-family="Arial, sans-serif">${text(24,32,title,{size:24,weight:700,width:Math.floor((w-48)/13)})}${text(24,34+t.length*32,subtitle,{size:16,width:Math.floor((w-48)/8),color:c.muted})}${content.body}</g></svg>`;}
export function columns(title,subtitle,lanes,ctx={},foot=''){return canvas(title,subtitle,ctx,({w,c,top})=>{const cols=w<640?1:Math.min(3,lanes.length),gap=20,cw=(w-48-gap*(cols-1))/cols;let y=top,body='';for(let start=0;start<lanes.length;start+=cols){let bottom=y;for(let j=0;j<cols&&start+j<lanes.length;j++){const lane=lanes[start+j],x=24+j*(cw+gap),chars=Math.max(12,Math.floor((cw-20)/9));let yy=y+30;body+=`<path d="M${x} ${y} H${x+cw}" stroke="${e(c.accent)}" stroke-width="3"/>`+text(x+8,yy,lane.label,{size:18,weight:700,width:chars});yy+=wrap(lane.label,chars).length*25+6;for(const item of lane.items){const title=typeof item==='string'?item:item.title,detail=typeof item==='string'?'':item.detail;body+=text(x+8,yy,title,{size:18,weight:600,width:chars});yy+=wrap(title,chars).length*25;if(detail){body+=text(x+8,yy+4,detail,{size:16,width:chars,color:c.muted});yy+=wrap(detail,chars).length*23+8;}body+=`<path d="M${x+8} ${yy+9} H${x+cw-8}" stroke="${e(c.line)}"/>`;yy+=22;}if(!lane.items.length){body+=text(x+8,yy,'None',{size:16});yy+=30;}bottom=Math.max(bottom,yy);}y=bottom+12;}if(foot){body+=text(24,y,foot,{size:15,width:Math.floor((w-48)/8),color:c.muted});y+=wrap(foot,Math.floor((w-48)/8)).length*22;}return{body,end:y};});}
export function pathways(title,subtitle,paths,ctx={},foot=''){return canvas(title,subtitle,ctx,({w,c,top})=>{let y=top,body='';const horizontal=w>=700;for(const steps of paths){let x=24,max=y;const cw=horizontal?(w-88)/steps.length:w-48;for(let i=0;i<steps.length;i++){const step=steps[i],chars=Math.max(18,Math.floor((cw-12)/9)),lines=wrap(step.value,chars),h=lines.length*25+58;body+=text(x+6,y+20,step.label,{size:15,weight:700,width:chars,color:c.accent})+text(x+6,y+52,step.value||'Not written',{size:18,width:chars});body+=`<path d="M${x} ${y+32} H${x+cw}" stroke="${e(c.line)}"/>`;max=Math.max(max,y+h);if(i<steps.length-1){if(horizontal){body+=text(x+cw+5,y+55,'→',{size:20});x+=cw+20;}else{body+=text(x+10,y+h+9,'↓',{size:22,color:c.accent});y+=h+25;}}}y=horizontal?max+16:Math.max(y,max)+16;}if(foot){body+=text(24,y,foot,{size:15,width:Math.floor((w-48)/8),color:c.muted});y+=wrap(foot,Math.floor((w-48)/8)).length*22;}return{body,end:y};});}
export function responsiveChart(title,subtitle,series,ctx={},foot='',metrics=[]){return canvas(title,subtitle,ctx,({w,c,top})=>{let svg=lineChart(series.map((s,i)=>({...s,color:i?c.muted:c.accent})),{width:w-48,height:250,min:Math.min(0,...series.flatMap(s=>s.values))});svg=svg.replace('aria-hidden="true"',`x="24" y="${top}" width="${w-48}" height="250"`).replaceAll('var(--line)',c.line).replaceAll('var(--line-strong)',c.muted);let y=top+278;const chars=Math.floor((w-48)/9);for(const s of series){svg+=text(24,y,s.label,{size:16,width:chars,color:s===series[0]?c.accent:c.muted});y+=wrap(s.label,chars).length*23;}for(const value of metrics){svg+=text(24,y+10,value,{size:18,width:chars});y+=wrap(value,chars).length*25+18;}svg+=text(24,y+10,foot,{size:15,width:Math.floor((w-48)/8),color:c.muted});return{body:svg,end:y+wrap(foot,Math.floor((w-48)/8)).length*22+20};});}

// Preserve native reducers when an interaction changes interpretation or lineage.
export function mutate(state,apply,action){const next=clone(state);apply(next,action);return next;}
export function workspaceAction(state,apply,action){const session={version:1,activeId:state.id,workspaces:[clone(state)]};return apply(session,action).workspaces[0];}
export function nextId(items,prefix='article'){let n=1;while(items.some(x=>x.id===prefix+n))n++;return prefix+n;}
export function recordSchema(example){return{type:'object',additionalProperties:shape(example)};}
