/* Network-first with full precache: the whole suite is cached at install, so an
   installed app works offline after ONE online launch (iOS home-screen apps get
   isolated storage — the Safari-tab service worker doesn't carry over, so lazy
   visited-page caching wasn't enough; Matt hit exactly that on 2026-07-06).
   Online requests still go network-first, so the auto-deploying site never
   serves stale pages when connected. /api/ (gauge relay) stays live-only.
   PRECACHE is generated from the filesystem; dev/pwa-precache.test.mjs fails
   if a shipped file is missing from it. */
const CACHE = 'tools-71423da55c';
const PRECACHE = [
  '/',
  '/alarm/',
  '/alarm/app.js',
  '/alarm/engine.js',
  '/alarm/gate-canvas.js',
  '/alarm/interaction.js',
  '/alarm/motion-spec.js',
  '/alarm/render.js',
  '/alarm/style.css',
  '/assets/about.css',
  '/assets/app-common.js',
  '/assets/controls.css',
  '/assets/edit-in-place.js',
  '/assets/editor-common.js',
  '/assets/energy.css',
  '/assets/exports.js',
  '/assets/handoff-ui.js',
  '/assets/handoff.css',
  '/assets/handoff.js',
  '/assets/icons/apple-touch-icon.png',
  '/assets/icons/icon-192.png',
  '/assets/icons/icon-512.png',
  '/assets/icons/icon-maskable-512.png',
  '/assets/mobile.css',
  '/assets/mobile.js',
  '/assets/motion.css',
  '/assets/motion.js',
  '/assets/narrow-width.js',
  '/assets/page.css',
  '/assets/popover-focus.js',
  '/assets/projection-basis.js',
  '/assets/pwa.js',
  '/assets/saved-items.js',
  '/assets/schedule.js',
  '/assets/series.js',
  '/assets/snapshots.js',
  '/assets/svg.js',
  '/assets/syntax-try.js',
  '/assets/syntax.css',
  '/assets/tokens.css',
  '/assets/verdict-edit.js',
  '/assets/verdict-svg.js',
  '/assets/verdict.js',
  '/assets/workspace.css',
  '/assets/workspace.js',
  '/bets/',
  '/bets/app.js',
  '/bets/diff.js',
  '/bets/edit-targets.js',
  '/bets/editor.js',
  '/bets/engine.js',
  '/bets/layout.js',
  '/bets/motion-spec.js',
  '/bets/parse.js',
  '/bets/render-presentation.js',
  '/bets/render-quadrant.js',
  '/bets/render.js',
  '/bets/style.css',
  '/case/',
  '/case/app.js',
  '/case/edit-targets.js',
  '/case/editor.js',
  '/case/parse.js',
  '/case/planning-context.js',
  '/case/render.js',
  '/duel/',
  '/duel/app.js',
  '/duel/engine.js',
  '/duel/render.js',
  '/duel/style.css',
  '/fermi/',
  '/fermi/app.js',
  '/fermi/cashflow.js',
  '/fermi/debt.js',
  '/fermi/engine.js',
  '/fermi/histlayout.js',
  '/fermi/interactions.js',
  '/fermi/pour.js',
  '/fermi/render-cashflow.js',
  '/fermi/render-driver.js',
  '/fermi/solve.js',
  '/fermi/state.js',
  '/flow/',
  '/flow/app.js',
  '/flow/dice.js',
  '/flow/economics.js',
  '/flow/engine.js',
  '/flow/expedite.js',
  '/flow/motion-runtime.js',
  '/flow/motion-spec.js',
  '/flow/render.js',
  '/gauge/',
  '/gauge/app.js',
  '/gauge/draft.js',
  '/gauge/edit-targets.js',
  '/gauge/editor.js',
  '/gauge/engine.js',
  '/gauge/handoff.js',
  '/gauge/import-state.js',
  '/gauge/motion-spec.js',
  '/gauge/parse.js',
  '/gauge/relay-client.js',
  '/gauge/render-form.js',
  '/gauge/render-overlay.js',
  '/gauge/safety.js',
  '/gauge/session.js',
  '/gauge/style.css',
  '/manifest.webmanifest',
  '/map/',
  '/map/app.js',
  '/map/diff.js',
  '/map/edit-targets.js',
  '/map/editor.js',
  '/map/handoff.js',
  '/map/interactions.js',
  '/map/layout.js',
  '/map/motion-spec.js',
  '/map/parse.js',
  '/map/readout.js',
  '/map/render-presentation.js',
  '/map/render.js',
  '/map/style.css',
  '/map/zones.js',
  '/paths/',
  '/paths/app.js',
  '/paths/artefact-parts.js',
  '/paths/edit-targets.js',
  '/paths/evaluate.js',
  '/paths/handoff-roadmap.js',
  '/paths/inspector.js',
  '/paths/layout-tree.js',
  '/paths/learning-agenda.js',
  '/paths/learning-closeout.js',
  '/paths/overview.js',
  '/paths/parse.js',
  '/paths/plans.js',
  '/paths/project.js',
  '/paths/render-conditions.js',
  '/paths/render-dependencies.js',
  '/paths/render-learning-agenda.js',
  '/paths/render-learning-closeout.js',
  '/paths/render-overview.js',
  '/paths/render-plans.js',
  '/paths/render-question-lens.js',
  '/paths/render-tree.js',
  '/paths/style.css',
  '/paths/tree.js',
  '/paths/verdict.js',
  '/premortem/',
  '/premortem/app.js',
  '/premortem/register.js',
  '/premortem/render-board.js',
  '/premortem/render-register.js',
  '/premortem/render-wizard.js',
  '/premortem/store.js',
  '/premortem/style.css',
  '/premortem/wizard.js',
  '/proxy/',
  '/proxy/app.js',
  '/proxy/editor.js',
  '/proxy/example.js',
  '/proxy/export-projection.js',
  '/proxy/parse.js',
  '/proxy/project.js',
  '/proxy/render-hunt.js',
  '/proxy/style.css',
  '/rank/',
  '/rank/app.js',
  '/rank/engine.js',
  '/rank/examples.js',
  '/roadmap/',
  '/roadmap/app.js',
  '/roadmap/board-window.js',
  '/roadmap/cond-parts.js',
  '/roadmap/deck-parts.js',
  '/roadmap/edit-targets.js',
  '/roadmap/edit.js',
  '/roadmap/editor.js',
  '/roadmap/export-pages.js',
  '/roadmap/handoff-paths.js',
  '/roadmap/interactions.js',
  '/roadmap/layout.js',
  '/roadmap/markdown.js',
  '/roadmap/motion-spec.js',
  '/roadmap/pack.js',
  '/roadmap/parse.js',
  '/roadmap/render-board.js',
  '/roadmap/render-deck-pages.js',
  '/roadmap/render-deck.js',
  '/roadmap/render-focus.js',
  '/roadmap/render-register.js',
  '/roadmap/render.js',
  '/roadmap/style.css',
  '/roadmap/text-parts.js',
  '/roadmap/vendor/codemirror.js',
  '/signal-vs-noise/',
  '/signal-vs-noise/app.js',
  '/signal-vs-noise/engine.js',
  '/signal-vs-noise/interaction.js',
  '/signal-vs-noise/render.js',
  '/signal-vs-noise/style.css',
  '/timeline/',
  '/timeline/app.js',
  '/timeline/diff.js',
  '/timeline/edit-targets.js',
  '/timeline/editor.js',
  '/timeline/handoff.js',
  '/timeline/layout.js',
  '/timeline/lrm.js',
  '/timeline/mergebias.js',
  '/timeline/motion-spec.js',
  '/timeline/parse.js',
  '/timeline/render.js',
  '/timeline/style.css',
  '/tree/',
  '/tree/app.js',
  '/tree/comparison.js',
  '/tree/edit-targets.js',
  '/tree/editor.js',
  '/tree/engine.js',
  '/tree/format.js',
  '/tree/layout.js',
  '/tree/motion-spec.js',
  '/tree/parse.js',
  '/tree/render-density.js',
  '/tree/render.js',
  '/tree/style.css',
  '/wardley/',
  '/wardley/app.js',
  '/wardley/drag-click-guard.js',
  '/wardley/edit-targets.js',
  '/wardley/editor.js',
  '/wardley/layout.js',
  '/wardley/motion-spec.js',
  '/wardley/parse.js',
  '/wardley/render.js',
  '/wardley/style.css',
  '/why/',
  '/why/app-menu.js',
  '/why/app.js',
  '/why/diff.js',
  '/why/edit-targets.js',
  '/why/editor.js',
  '/why/motion-spec.js',
  '/why/parse.js',
  '/why/project.js',
  '/why/render-map.js',
  '/why/render-ost.js',
  '/why/render-presentation.js',
  '/why/style.css'
];

self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE)
    .then(c => Promise.allSettled(PRECACHE.map(u => c.add(u))))
    .then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => e.waitUntil(
  caches.keys()
    .then(keys => Promise.all(keys.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim())
));
self.addEventListener('fetch', e => {
  const req = e.request;
  const url = new URL(req.url);
  if(req.method !== 'GET' || url.origin !== location.origin) return;
  if(url.pathname.startsWith('/api/')) return;
  e.respondWith(
    fetch(req).then(res => {
      if(res.ok){
        const copy = res.clone();
        caches.open(CACHE).then(c => c.put(req, copy));
      }
      return res;
    }).catch(() => caches.match(req)
      .then(m => m || caches.match(url.pathname.replace(/\/$/, '/') === url.pathname ? url.pathname + 'index.html' : '/')))
  );
});
