import {exposure} from '../../premortem/register.js';
import {renderRegister} from '../../premortem/render-register.js';
import {base,object,text,num,int,tuple,array,choice,range,htmlStyle} from './classic-shared.js';
const date='2026-10-03T00:00:00.000Z';
const risk=(id,label,p,impact)=>({id,text:label,kind:'risk',tag:null,cluster:null,essential:false,p,impact,actions:[],votes:0,status:'open',created:date,lastReviewed:date});
const entry=object({id:text(60,1),text:text(240,1),kind:choice(['risk']),tag:{type:'null'},cluster:{type:'null'},essential:{const:false},p:tuple([num(0,100),num(0,100)]),impact:tuple([num(0,1e6),num(0,1e6)]),actions:array(object({text:text(240),owner:text(100),done:{type:'boolean'},votes:choice([0])}),0,8),votes:choice([0]),status:choice(['open','mitigating','closed']),created:text(30,10),lastReviewed:text(30,10)});
export const definition=base('premortem','Premortem','Explore a risk register with uncertain likelihood and impact.',
 {v:1,id:'article-launch',title:'Reading app launch',question:'It is launch plus 90 days and the launch failed. Why?',unit:'£k',people:5,phase:'REGISTER',entries:[risk('onboarding','New onboarding loses readers',[30,55],[60,180]),risk('sync','Sync rewrite loses reading positions',[10,30],[100,400]),risk('review','Store review rejects the referral mechanic',[15,35],[30,120])]},
 object({v:choice([1]),id:text(60,1),title:text(180),question:text(240),unit:text(20),people:int(1,50),phase:choice(['REGISTER']),entries:array(entry,1,12)}),
 {'likelihood-high':range('First risk likelihood, high estimate (%)',['entries',0,'p',1],30,100,5),'impact-high':range('First risk impact, high estimate (£k)',['entries',0,'impact',1],60,500,10)},
 {register:{title:'Risk register',description:'Native exposure ranking with explicit independence assumptions.',controls:['likelihood-high','impact-high'],render(s,ctx){const exp=exposure(s.entries),now=new Date(ctx.today||'2026-10-03');return {html:htmlStyle+'<style>.embed-classic .registerwrap{overflow:auto}.embed-classic .register{min-width:600px}.embed-classic .regplane{display:block;font-weight:700}.embed-classic .bandtext{display:block;font-size:12px}.embed-classic .portfolio{font-size:14px}</style><section class="embed-classic">'+renderRegister(s,exp,now,{interactive:false})+'</section>',summary:'Illustrative risk register for '+s.title+'. Median portfolio exposure '+exp.portfolio.p50.toPrecision(3)+' '+s.unit+' under stated likelihood and impact ranges. The simulation assumes independent risks; correlated risks can stack higher.'};}}},
 s=>{if(new Set(s.entries.map(e=>e.id)).size!==s.entries.length)throw new Error('Risk identifiers must be distinct.');for(const e of s.entries){if(!/^[a-zA-Z0-9-]+$/.test(e.id))throw new Error('Risk identifiers must contain only letters, digits and hyphens.');if(e.p[0]>e.p[1]||e.impact[0]>e.impact[1])throw new Error('Risk ranges must be ordered.');if(!Number.isFinite(Date.parse(e.created))||!Number.isFinite(Date.parse(e.lastReviewed)))throw new Error('Risk review dates must be valid dates.');}});

definition.views['register'].defaultControls=['likelihood-high'];
