/* A release owns one complete, immutable cache. Keeping the lifecycle ordinary
   (no skipWaiting/claim) lets already-open pages finish with their own modules. */
import {createHash} from 'node:crypto';

export function integrity(bytes){
  return 'sha256-' + createHash('sha256').update(bytes).digest('base64');
}

function registerRelease(){
  self.addEventListener('install', event => {
    event.waitUntil((async () => {
      const cache = await caches.open(CACHE);
      try{
        // addAll commits atomically. Integrity rejects a stale CDN response or a
        // deployment changing midway through installation, even with HTTP 200.
        await cache.addAll(PRECACHE.map(url => new Request(url, {
          cache: 'reload', integrity: INTEGRITY[url],
        })));
      }catch(error){
        await caches.delete(CACHE);
        throw error;
      }
    })());
  });
  self.addEventListener('activate', event => {
    event.waitUntil(caches.keys().then(keys => Promise.all(
      keys.filter(key => key.startsWith(PREFIX + '-') && key !== CACHE)
        .map(key => caches.delete(key))
    )));
  });
  self.addEventListener('fetch', event => {
    const request = event.request;
    const url = new URL(request.url);
    if(request.method !== 'GET' || url.origin !== location.origin ||
       url.pathname === '/api' || url.pathname.startsWith('/api/')) return;
    const path = url.pathname.replace(/\/index\.html$/, '/');
    if(!Object.hasOwn(INTEGRITY, path)){
      if(request.mode === 'navigate' && Object.hasOwn(INTEGRITY, path + '/')){
        url.pathname += '/';
        event.respondWith(Promise.resolve(Response.redirect(url.href, 302)));
      }
      return;
    }
    // Search strings and URL-state fragments do not select a different static
    // release. Never repair a missing entry with unverified current network bytes.
    event.respondWith(caches.open(CACHE).then(cache => cache.match(path))
      .then(response => response || Response.error()));
  });
}

export function generateWorker(prefix, entries){
  const sorted = [...entries].sort((a, b) => a.url.localeCompare(b.url, 'en'));
  const runtime = registerRelease.toString();
  const revision = createHash('sha256').update(JSON.stringify(sorted) + runtime)
    .digest('hex').slice(0, 20);
  return `/* Generated by node dev/gen-sw.mjs. Do not edit. */\n` +
    `const PREFIX = '${prefix}';\nconst CACHE = '${prefix}-${revision}';\n` +
    `const PRECACHE = [\n  ${sorted.map(e => `'${e.url}'`).join(',\n  ')}\n];\n` +
    `const INTEGRITY = ${JSON.stringify(Object.fromEntries(sorted.map(e => [e.url, e.integrity])), null, 2)};\n` +
    `(${runtime})();\n`;
}
