import {CAPABILITIES,TEAM_NAMES,DEFAULT_LAYOUT,DEFAULT_ASSUMPTIONS,simulate} from '../../lab/dist/teams/engine.js';
import {validatePortable,activeWorkload} from '../../lab/dist/teams/library.js';
import {base,clone,select,columns,number,nativeSchema} from './_lab.js';
const initial={layout:clone(DEFAULT_LAYOUT),names:clone(TEAM_NAMES),scenario:'rush',assumptions:clone(DEFAULT_ASSUMPTIONS),day:10,trace:null,baseline:{layout:clone(DEFAULT_LAYOUT),names:clone(TEAM_NAMES)},workloads:[],designs:[]};
const validate=s=>validatePortable({format:'thinking-lab-teams',version:1,session:s});
const controls=Object.fromEntries(CAPABILITIES.map(c=>[c.id,select(c.name+' team',['layout',c.id],TEAM_NAMES)]));
export const definition=base('teams','How teams fit the work','Move capabilities across boundaries and replay identical work.',initial,validate,{'handoffs':{title:'Boundaries and waiting',description:'The same six specialists face the same workload in both arrangements.',controls:Object.keys(controls),render(s,ctx){const r=simulate({...s,scenario:activeWorkload(s)}),b=s.baseline?simulate({...s,layout:s.baseline.layout,scenario:activeWorkload(s)}):null;const f=r.final;const lanes=Object.entries(s.names).map(([id,label])=>({label,items:CAPABILITIES.filter(c=>s.layout[c.id]===id).map(c=>({title:c.name,detail:'One specialist'}))}));const rows=[];rows.push({label:'After 30 days',value:`${f.completed} completed · ${f.unfinished} unfinished · ${number(f.medianLeadTime)} days median lead time · ${f.handoffs} handoffs`});if(b)rows.push({label:'Pinned arrangement · same workload',value:`${b.final.completed} completed · ${b.final.unfinished} unfinished · ${number(b.final.medianLeadTime)} days median lead time · ${b.final.handoffs} handoffs`});return{svg:columns('How teams fit the work','Six specialists · move a capability across the team boundaries',lanes,ctx,rows.map(x=>x.label+': '+x.value).join('\n')+'\nLead time includes completed work only. Shared coordination/boundary assumptions are illustrative.'),summary:rows.map(x=>x.label+': '+x.value).join(' ')};}}},controls,{},nativeSchema(initial));
export const toToolState=clone;
export const fromToolState=clone;
