/* Case's source-backed native forms replace its former SVG edit-in-place surface.
   These flows cover the same phone/keyboard/undo contract plus reference history. */
import {chromium} from 'playwright';
import {trackErrors, report, tally, until, untilValue} from './_harness.mjs';
const BASE=process.env.BASE||'http://localhost:8087';
const browser=await chromium.launch();
const page=await browser.newPage({viewport:{width:1500,height:1000}});
const errors=trackErrors(page),results=[];
const check=(name,ok)=>results.push((ok?'PASS ':'FAIL ')+name);
const doc=()=>page.evaluate(()=>localStorage.getItem('case-src'));
await page.goto(BASE+'/case/',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Edit source',exact:true}).click();
await page.getByRole('button',{name:'Morrow · paid tier',exact:true}).click();
await until(doc);
const original=await doc();
await page.getByRole('button',{name:'Edit source',exact:true}).click();
check('Brief separates the approved pilot from the unresolved launch',(await page.locator('#preview').textContent()).includes('Paid-tier launch remains undecided'));
await page.locator('[data-kind="claim"]').first().focus();
await page.keyboard.press('Enter');
check('keyboard selection opens its reason inspector',await page.getByRole('button',{name:'Edit reason',exact:true}).isVisible());
// CodeMirror groups edits within 500ms; isolate the form transaction from fixture load.
await page.waitForTimeout(550);
await page.getByRole('button',{name:'Edit reason',exact:true}).click();
await page.getByLabel('Qualification',{exact:true}).fill('Conditional on the authored inputs; no guarantee.');
await page.getByRole('button',{name:'Save changes',exact:true}).click();
await untilValue(doc,d=>d.includes('no guarantee.'));
check('native form updates portable source',(await doc()).includes('qualification: Conditional on the authored inputs; no guarantee.'));
const edited=await doc();
await page.getByRole('button',{name:'Edit source',exact:true}).click();
await page.locator('.cm-content').click();await page.keyboard.press('ControlOrMeta+z');
await untilValue(doc,d=>d!==edited);
check('one undo restores the exact pre-form source',(await doc())===original);
await page.getByRole('button',{name:'Edit source',exact:true}).click();
await page.getByRole('button',{name:'Compare',exact:true}).click();
await untilValue(doc,d=>d.includes('view: compare'));
check('view picker edits the DSL',(await doc()).includes('view: compare'));
check('comparison exposes conditions and downside',(await page.locator('#preview').textContent()).includes('What must be true'));
await page.locator('#appearance summary').click();
await page.getByLabel('Typography',{exact:true}).selectOption('dm-sans');
await untilValue(doc,d=>d.includes('font: dm-sans'));
await page.getByLabel('Theme',{exact:true}).selectOption('dark');
await untilValue(doc,d=>d.includes('theme: dark'));
check('font and theme use the same source',(await doc()).includes('font: dm-sans')&&(await page.locator('html').getAttribute('data-theme'))==='dark');
await page.locator('#appearance summary').click();
await page.getByRole('button',{name:'Brief',exact:true}).click();
await untilValue(doc,d=>d.includes('view: brief'));
await until(()=>page.getByRole('button',{name:'Replace reference',exact:true}).count());
await page.getByRole('button',{name:'Replace reference',exact:true}).click();
await page.getByLabel('New reference URL',{exact:true}).fill('https://example.com/pilot-review');
await page.getByRole('button',{name:'Compare references',exact:true}).click();
await until(()=>page.locator('#referencecomparison').isVisible());
check('replacement reveals both references before adoption',(await page.locator('#previousstate').inputValue()).includes('title:')&&(await page.locator('#nextstate').inputValue()).includes('External reference'));
await page.getByLabel('What changed?',{exact:true}).fill('Pilot costs increased.');
await page.getByLabel('What does this mean for the decision?',{exact:true}).fill('Revisit the pilot budget before approval.');
await page.getByRole('button',{name:'Adopt reference and record review',exact:true}).click();
await untilValue(doc,d=>d.includes('previous:'));
const reviewed=await doc();
check('adoption keeps previous reference and adds a dated review',/previous: (?:https:\/\/[^/]+)?\/tree\/#/.test(reviewed)&&reviewed.includes('url: https://example.com/pilot-review')&&reviewed.includes('review '));
check('reference adoption does not silently revise authorisation',reviewed.split('\n').find(l=>l.startsWith('decision:'))===original.split('\n').find(l=>l.startsWith('decision:')));
await page.getByRole('button',{name:'Reviews',exact:true}).click();
await untilValue(doc,d=>d.includes('view: review'));
check('dated review shows change and implication',(await page.locator('#preview').textContent()).includes('Pilot costs increased.'));
await until(()=>page.url().includes('#'));
await until(async()=>{const {decodeHash}=await import('../../assets/series.js');return (await decodeHash(page.url().split('#')[1])).t===await doc();});
const roundtrip=await browser.newPage();await roundtrip.goto(page.url(),{waitUntil:'networkidle'});
await roundtrip.locator('#preview svg').waitFor();
await roundtrip.getByRole('button',{name:'Edit source',exact:true}).click();
const sourceDownload=roundtrip.waitForEvent('download');await roundtrip.getByRole('button',{name:'Save source',exact:true}).click();
const sourceFile=await sourceDownload;const {readFile:readSource}=await import('node:fs/promises');
check('URL reopens the reviewed source exactly',await readSource(await sourceFile.path(),'utf8')===await doc());
await roundtrip.close();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Brief',exact:true}).click();
await untilValue(doc,d=>d.includes('view: brief'));
check('phone page has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await page.locator('[data-kind="claim"]').first().click();
await page.getByRole('button',{name:'Edit reason',exact:true}).click();
check('phone selected reason has a usable native editor',await page.getByLabel('Qualification',{exact:true}).isVisible());
await page.getByRole('button',{name:'Cancel',exact:true}).click();
await page.getByRole('button',{name:'Close detail',exact:true}).click();
await page.setViewportSize({width:1500,height:1000});
await page.getByRole('button',{name:'Export deck',exact:true}).click();
await until(()=>page.locator('#deckdialog').isVisible());
check('deck preview has a real 16:9 slide',await page.locator('#deckcanvas svg').getAttribute('viewBox')==='0 0 1600 900');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'SVG slides',exact:true}).click();
const file=await download;const {readFile}=await import('node:fs/promises');const zip=await readFile(await file.path());
check('SVG deck ZIP includes source and embedded typography',zip.includes(Buffer.from('case-source.txt'))&&zip.includes(Buffer.from('data-chapter-fonts="embedded"'))&&zip.readUInt32LE(0)===0x04034b50);
if(errors.length)console.log('Browser errors:',errors);
check('no console or page errors',errors.length===0);
await browser.close();console.log(results.join('\n'));report('case',{...tally(results),min:17});
