/* Real browser lifecycle against two fixture releases generated by production code. */
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {chromium} from 'playwright';
import {generateWorker, integrity} from '../sw-release.mjs';
import {report} from './_harness.mjs';

const browser = await chromium.launch();
let passed = 0;
try{
  for(const prefix of ['tools', 'energy']){
    let release = 'A';
    let broken = null;
    const pagePath = prefix === 'tools' ? '/roadmap/' : '/risk/';
    const files = version => new Map([
      ['/', `<script src="/register.js"></script><script type="module" src="/app.js"></script><p>Fixture</p>`],
      [pagePath, `<script src="/register.js"></script><script type="module" src="/app.js"></script><p>Fixture</p>`],
      ['/register.js', `window.installState = navigator.serviceWorker.register('/sw.js').then(registration =>
        new Promise((resolve, reject) => {
          const worker = registration.installing || registration.waiting || registration.active;
          const deadline = setTimeout(() => reject(new Error('Worker installation did not settle')), 10000);
          const settled = () => {
            if(['activated', 'redundant'].includes(worker.state)){
              clearTimeout(deadline);
              resolve(worker.state);
            }
          };
          worker.addEventListener('statechange', settled);
          settled();
        }));`],
      ['/app.js', `window.release = '${version}'; window.lazy = () => import('/lazy.js').then(m => m.release);`],
      ['/lazy.js', `export const release = '${version}';`],
    ]);
    const worker = version => generateWorker(prefix, [...files(version)].map(([url, body]) => ({url, integrity: integrity(body)})));
    const cacheName = version => worker(version).match(/const CACHE = '([^']+)'/)[1];
    const server = createServer((req, res) => {
      const path = new URL(req.url, 'http://localhost').pathname;
      res.setHeader('Cache-Control', 'no-store');
      if(path === '/sw.js'){
        res.setHeader('Content-Type', 'text/javascript');
        return res.end(worker(release));
      }
      if(path === '/api/room' || path === '/live') return res.end(release);
      if(path === '/lazy.js' && broken === 'missing'){
        res.statusCode = 404;
        return res.end('Missing');
      }
      const body = files(path === '/lazy.js' && broken === 'stale' ? 'A' : release).get(path);
      res.setHeader('Content-Type', path.endsWith('.js') ? 'text/javascript' : 'text/html');
      res.statusCode = body === undefined ? 404 : 200;
      // Preview hosting injects toolbar HTML unless this request opts out. The
      // page itself still receives it; release precaching must receive source bytes.
      const toolbar = body !== undefined && !path.endsWith('.js') &&
        req.headers['x-vercel-skip-toolbar'] !== '1'
        ? '<script data-vercel-toolbar>window.toolbarInjected = true;</script>' : '';
      res.end((body ?? 'Not found') + toolbar);
    });
    await new Promise(resolve => server.listen(0, '127.0.0.1', resolve));
    const base = 'http://127.0.0.1:' + server.address().port;
    const ctx = await browser.newContext();
    try{
      const page = await ctx.newPage();
      await page.goto(base);
      assert.equal(await page.evaluate(() => window.toolbarInjected), true,
        'ordinary preview navigation receives injected toolbar HTML');
      assert.equal(await page.evaluate(() => window.installState), 'activated',
        'toolbar injection is excluded from integrity-checked precaching');
      assert.equal(await page.evaluate(() => caches.match('/').then(r => r.text())), files('A').get('/'),
        'cached HTML contains exactly the generated release bytes');
      passed++;
      assert.equal(await page.evaluate(() => navigator.serviceWorker.controller === null), true,
        'first install does not take over a document loaded from the network');
      await page.reload();
      await page.waitForFunction(() => window.release === 'A' && navigator.serviceWorker.controller);
      await page.evaluate(() => caches.open('unrelated-cache'));
      assert.equal(await page.evaluate(() => fetch('/lazy.js').then(r => r.text())), files('A').get('/lazy.js'));
      release = 'B';
      async function update(){
        return page.evaluate(async () => {
          const registration = await navigator.serviceWorker.getRegistration();
          const settled = new Promise(resolve => registration.addEventListener('updatefound', () => {
            const worker = registration.installing;
            worker.addEventListener('statechange', () => {
              if(['installed', 'redundant'].includes(worker.state)) resolve(worker.state);
            });
          }, {once: true}));
          await registration.update();
          return settled;
        });
      }
      for(const failure of ['missing', 'stale']){
        broken = failure;
        assert.equal(await update(), 'redundant', failure + ' resource prevents installation');
        assert.equal(await page.evaluate(name => caches.has(name), cacheName('B')), false,
          'failed install leaves no partial release cache');
        assert.equal(await page.evaluate(() => fetch('/lazy.js').then(r => r.text())), files('A').get('/lazy.js'),
          'failed release cannot replace a working cached module');
        passed++;
      }
      broken = null;
      assert.equal(await update(), 'installed');
      assert.equal(await page.evaluate(() => window.lazy()), 'A',
        'old document lazy import remains on its original release after deployment');
      assert.equal(await page.evaluate(() => fetch('/api/room').then(r => r.text())), 'B', 'relay bypasses release cache');
      assert.equal(await page.evaluate(() => fetch('/live').then(r => r.text())), 'B', 'unlisted resource stays network-only');
      assert.equal(await page.evaluate(() => caches.match('/live').then(Boolean)), false);
      const second = await ctx.newPage();
      await second.goto(base + pagePath + '?example=one#state');
      await second.waitForFunction(() => window.release === 'A');
      const waiting = ctx.serviceWorkers().find(w => w !== ctx.serviceWorkers()[0]);
      assert.ok(waiting, 'second generation exists');
      // Keep no controlled clients alive: natural activation is the release boundary.
      await page.close();
      await second.close();
      await waiting.evaluate(() => new Promise(resolve => {
        const worker = self.registration.waiting || self.registration.active;
        if(worker.state === 'activated') return resolve();
        worker.addEventListener('statechange', () => { if(worker.state === 'activated') resolve(); });
      }));
      const fresh = await ctx.newPage();
      await fresh.goto(base + pagePath + '?example=two#saved-state');
      await fresh.waitForFunction(() => window.release === 'B');
      assert.equal(await fresh.evaluate(() => window.lazy()), 'B');
      assert.deepEqual((await fresh.evaluate(() => caches.keys())).sort(), [cacheName('B'), 'unrelated-cache'].sort(),
        'activation removes only obsolete caches owned by this worker');
      await ctx.setOffline(true);
      await fresh.goto(base + pagePath + 'index.html?example=offline#saved-state');
      await fresh.waitForFunction(() => window.release === 'B');
      assert.equal(await fresh.evaluate(() => window.lazy()), 'B');
      await fresh.goto(base + pagePath.slice(0, -1) + '?example=bare#saved-state');
      await fresh.waitForFunction(() => window.release === 'B');
      assert.ok(fresh.url().includes(pagePath + '?example=bare#saved-state'));
      assert.equal(await fresh.evaluate(() => fetch('/api/room').then(() => true, () => false)), false);
      assert.equal(await fresh.evaluate(() => fetch('/live').then(() => true, () => false)), false);
      // Cache loss must fail closed rather than mix in a network deployment.
      await ctx.setOffline(false);
      await fresh.evaluate(async name => (await caches.open(name)).delete('/lazy.js'), cacheName('B'));
      assert.equal(await fresh.evaluate(() => fetch('/lazy.js').then(() => true, () => false)), false);
      passed++;
      console.log('PASS ' + prefix + ': atomic install, failed upgrade, deferred activation, coherent modules, toolbar exclusion and offline URLs');
    }finally{
      await ctx.close();
      await new Promise(resolve => server.close(resolve));
    }
  }
}finally{
  await browser.close();
}
report('pwa-upgrade', {pass: passed, fail: 0, min: 8});
